#!/usr/bin/env python

from functions import *

wioHumidityStamp = get_wio_sensor_data(NodeProperties.humidity, wio1_token)
wioTemperatureStamp = get_wio_sensor_data(NodeProperties.fahrenheit_degree, wio1_token)

data_dict = {NodeMap.humidity.value: wioHumidityStamp,
             NodeMap.temp.value: wioTemperatureStamp}

post_data_to_thinkspeak(data_dict)

post_data_to_initialstate(NodeMap.humidity.name, wioHumidityStamp)
post_data_to_initialstate(NodeMap.temp.name, wioTemperatureStamp)
