#!/usr/bin/env python

from functions import *
from mailer import main

wioMoistureStamp = get_wio_sensor_data(NodeProperties.moisture, wio_pete_token)

data_dict = {NodeMap.moisture.value: wioMoistureStamp}

post_data_to_thinkspeak(data_dict)

post_data_to_initialstate(NodeMap.moisture.name, wioMoistureStamp)

if wioMoistureStamp <= 450:
    main()
