#!/bin/bash

echo "
alias copy='xclip -sel clip'

alias bbo='sudo lxc-attach -n bbo'

alias leetserve='ssh leetserve.local'

alias cloneAutomation='sudo /home/gabeduke/repos/bbo_automation/web-automation/web-automation-core/src/main/resources/cloneAutomation/cloneAutomation.sh'

echo "Did you know that:"; whatis $(ls /bin | shuf -n 1)

function gitMerge() {
    git checkout $1
    git pull
    git checkout ${2:develop}
    git pull && git merge $1
}

function gitCreateBranch() {
git checkout -b $1 && git push --set-upstream origin $1
}


" >> ~/.bashrc