#!/bin/bash

echo "
alias copy='xclip -sel clip'

alias bbo='sudo lxc-attach -n bbo'

alias leetserve='ssh leetserve.local'

alias cloneAutomation='sudo /home/gabeduke/repos/bbo_automation/web-automation/web-automation-core/src/main/resources/cloneAutomation/cloneAutomation.sh'
" >> ~/.bashrc