#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 hugeFilePath startLine endLine" >&2
  exit 1
fi

sed -n -e $2','$3'p' -e $3'q' $1 > hfvim_temporary_file
vim hfvim_temporary_file
(head -n `expr $2 - 1` $1; cat hfnano_temporary_file; sed -e '1,'$3'd' $1) > hfvim_temporary_file2
cat hfvim_temporary_file2 > $1
rm hfvim_temporary_file hfvim_temporary_file2