#!/usr/bin/env bash


cd "$(dirname "$0")"

mkdir tmpdir
git clone --bare https://github.com/timelapseplus/VIEW.git tmpdir

pushd tmpdir
log=$(git log --date=iso \
    --since=`date --date='yesterday' +%Y-%m-%d` \
    --until=`date --date='tomorrow' +%Y-%m-%d` \
    --summary --show-notes --oneline --date-order)

echo "$log" >> "tmpFile.txt"
tmpFile.txt | slacktee
popd

rm -rf tmpdir
